      - name: no -a ipqmaxlen
        shell:
          cmd: |
            set -o pipefail
            no -a | awk '/ipqmaxlen/ && !/{{ var_ipqmaxlen }}/ {print $1,$3}'
        register: command_output
        when: ansible_distribution == 'AIX'
        changed_when: False
        tags: ipqmaxlen

      - debug:
          var=command_output.stdout_lines
        when: ansible_distribution == 'AIX' and command_output.stdout_lines
        tags: ipqmaxlen