      - name: no -a tcp_recvspace
        shell:
          cmd: |
            set -o pipefail
            no -a | awk '/tcp_recvspace/ && !/{{ var_tcp_recvspace }}/ {print $1,$3}'
        register: command_output
        when: ansible_distribution == 'AIX'
        changed_when: False
        tags: tcp_recvspace

      - debug:
          var=command_output.stdout_lines
        when: ansible_distribution == 'AIX' and command_output.stdout_lines
        tags: tcp_recvspace