      - name: AIX vscsi_path_to
        shell:
          chdir: /dev
          cmd: |
            set -o pipefail
            ls vscsi* | xargs -I % sh -c '{ echo %; lsattr -El %; }' | awk '/vscsi/ { if (flag == "0" ) {tmpvscsi=$1; flag=1 }} flag && /vscsi_path_to/ && !/{{ var_vscsi_path_to }}/ {print tmpvscsi,$1,$2; flag=0}'
        register: command_output
        when: ansible_distribution == 'AIX'
        changed_when: False
        tags: vscsi_path_to

      - debug:
          var=command_output.stdout_lines
        when: ansible_distribution == 'AIX' and command_output.stdout_lines
        tags: vscsi_path_to